### ISSUE TITLE
CONTINUATION_INDENT_SIZE

### ISSUE THREAD

**Issue by dotpack** [editorconfig/editorconfig-jetbrains#31]
Maybe CONTINUATION_INDENT_SIZE must be equal INDENT_SIZE?

```
# INDENT_SIZE = 2 (from .editorconfig file)
# CONTINUATION_INDENT_SIZE = 4 (from IDE config)

# Code looks good with INDENT_SIZE
angular.module('x').factory('y', function(z) {
  return {z: z};
});

# Code doesn't look good with INDENT_SIZE and CONTINUATION_INDENT_SIZE
angular
    .module('x')
    .factory('y', function (z) {
      return {z: z}
    });
```

What do you think about this?

**Comment by bellkev** [comment]
Ah, you see that I didn't implement "CONTINUATION_INDENT_SIZE" right? So that will just always be whatever it would normally be according to the JetBrains settings. Are you thinking that CONTINUATION_INDENT_SIZE should be set to whatever the editorconfig "indent_size" is? Or should there be a JetBrains-specific setting called "continuation_indent_size"? (I'm thinking the former makes more sense...)

**Comment by dotpack** [comment]
Thank you.
