### ISSUE TITLE
Re-add `insert_final_newline` support for repository installation version.

### ISSUE THREAD

**Issue by mrmachine** [editorconfig/editorconfig-jetbrains#42]
The README says it will be re-added soon (16 Dec 2013), and links to https://github.com/JetBrains/intellij-community/pull/139

That issue was closed and merged on 31 Dec 2013. So is there anything still preventing `insert_final_newline` support from being re-added?

This appears to be done already in the latest 0.4.0 release, which I can install manually. But it is not done for 0.3.1, which is what PyCharm installs when I follow the plugin repository installation instructions.

Thanks.

**Comment by denofevil** [comment]
I'll push 0.4.0 to the repository in the next couple of days

**Comment by bellkev** [comment]
Hey @denofevil, do you think you can push 0.4.0 soon? Or would you like me to?

As I recall, the reason for waiting on it was that it would still load in old versions of JetBrains IDEs and throw runtime exceptions despite the "since-build" attribute, and you were going to make sure that was the expected behavior. Did you find anything out about that? (Maybe the "since-build" is just used by the plugin repo infrastructure and not the plugin-loading code in the IDE?)

Also, @mrmachine, sorry for not mentioning this earlier, but for now you can download the zip file from the GitHub release (the green button on the left) and install the plugin manually for now, as described in the README.

**Comment by denofevil** [comment]
Sorry, it seems that I've forgotten to push it. I'm currently on vacation so I won't be able to push it until Tuesday. Feel free to push it if that's ok for you

**Comment by thasmo** [comment]
What's the status of this?

**Comment by bellkev** [comment]
Hey @thasmo 0.4.0 has been in the JetBrains plugin repo for a while. Sorry for not mentioning that in this thread.

**Comment by thasmo** [comment]
Ah, alright. :) Thanks @bellkev!
